"""add email column

Revision ID: 42a9ad35056a
Revises: 73bcfe3eb80e
Create Date: 2026-03-28 16:45:32.233940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42a9ad35056a'
down_revision: Union[str, Sequence[str], None] = '73bcfe3eb80e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainer_profiles')
    op.drop_table('users')
    op.drop_table('dim_agent')
    op.drop_table('tracker_profiles')
    op.drop_table('dim_date')
    op.drop_index(op.f('idx_conversations_session'), table_name='agent_conversations')
    op.drop_index(op.f('idx_conversations_user_agent'), table_name='agent_conversations')
    op.drop_table('agent_conversations')
    op.drop_table('dim_user')
    op.drop_index(op.f('idx_daily_tracking_user_date'), table_name='daily_tracking_entries')
    op.drop_table('daily_tracking_entries')
    op.drop_index(op.f('idx_vector_embeddings_embedding'), table_name='vector_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='ivfflat')
    op.drop_index(op.f('idx_vector_embeddings_user_category'), table_name='vector_embeddings')
    op.drop_table('vector_embeddings')
    op.drop_table('dietitian_profiles')
    op.drop_index(op.f('idx_fact_wellness_agent'), table_name='fact_wellness_metrics')
    op.drop_index(op.f('idx_fact_wellness_date'), table_name='fact_wellness_metrics')
    op.drop_index(op.f('idx_fact_wellness_user'), table_name='fact_wellness_metrics')
    op.drop_table('fact_wellness_metrics')
    op.drop_table('user_profiles')
    op.add_column('leads', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'email')
    op.create_table('user_profiles',
    sa.Column('profile_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender_identity', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('location_city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('location_region', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('location_country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('occupation', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('work_schedule', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('education_level', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('relationship_status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('family_structure', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('primary_language', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cultural_background', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('height_cm', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weight_kg', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('bmi', sa.NUMERIC(precision=3, scale=1), sa.Computed('(weight_kg / (((height_cm)::numeric / 100.0) * ((height_cm)::numeric / 100.0)))', persisted=True), autoincrement=False, nullable=True),
    sa.Column('medical_conditions', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('current_medications', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('supplements', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('physical_limitations', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('allergies_sensitivities', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('previous_health_events', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mental_health_challenges', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('therapy_experience', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mental_health_diagnoses', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('current_stress_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stress_triggers', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('current_coping_mechanisms', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('support_system_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('typical_daily_routine', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bedtime', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('wake_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('sleep_quality_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('work_life_balance_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('social_interaction_frequency', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('technology_usage_patterns', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('primary_wellness_goals', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('short_term_objectives', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('long_term_aspirations', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('previous_goal_experiences', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('motivation_triggers', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('accountability_preferences', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('completed_sections', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('profile_completion_percentage', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.CheckConstraint('current_stress_level >= 1 AND current_stress_level <= 10', name=op.f('user_profiles_current_stress_level_check')),
    sa.CheckConstraint('sleep_quality_rating >= 1 AND sleep_quality_rating <= 10', name=op.f('user_profiles_sleep_quality_rating_check')),
    sa.CheckConstraint('work_life_balance_rating >= 1 AND work_life_balance_rating <= 10', name=op.f('user_profiles_work_life_balance_rating_check')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('user_profiles_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', name=op.f('user_profiles_pkey'))
    )
    op.create_table('fact_wellness_metrics',
    sa.Column('fact_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_key', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_key', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('agent_key', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mood_score', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    sa.Column('energy_score', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    sa.Column('stress_score', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    sa.Column('sleep_quality_score', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    sa.Column('physical_activity_score', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    sa.Column('nutrition_adherence_score', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    sa.Column('overall_wellness_score', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    sa.Column('goal_achieved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('challenge_encountered', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('agent_interaction', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_key'], ['dim_agent.agent_key'], name=op.f('fact_wellness_metrics_agent_key_fkey')),
    sa.ForeignKeyConstraint(['date_key'], ['dim_date.date_key'], name=op.f('fact_wellness_metrics_date_key_fkey')),
    sa.ForeignKeyConstraint(['user_key'], ['dim_user.user_key'], name=op.f('fact_wellness_metrics_user_key_fkey')),
    sa.PrimaryKeyConstraint('fact_id', name=op.f('fact_wellness_metrics_pkey'))
    )
    op.create_index(op.f('idx_fact_wellness_user'), 'fact_wellness_metrics', ['user_key'], unique=False)
    op.create_index(op.f('idx_fact_wellness_date'), 'fact_wellness_metrics', ['date_key'], unique=False)
    op.create_index(op.f('idx_fact_wellness_agent'), 'fact_wellness_metrics', ['agent_key'], unique=False)
    op.create_table('dietitian_profiles',
    sa.Column('dietitian_profile_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('dietary_philosophy', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cultural_dietary_laws', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('food_allergies', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('food_intolerances', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('foods_to_avoid', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('preferred_cuisines', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('flavor_preferences', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('texture_preferences', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('food_aversions', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('diet_related_medical_conditions', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('medication_food_interactions', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('digestive_issues', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('weight_goals', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('body_composition_objectives', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('energy_level_patterns', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sleep_food_relationship', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cooking_skill_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cooking_confidence_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('available_cooking_equipment', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('kitchen_setup_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meal_prep_time_available', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('food_budget_monthly', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True),
    sa.Column('shopping_preferences', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('work_schedule_meal_constraints', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('local_food_availability', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('seasonal_preferences', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('cultural_food_traditions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('family_meal_patterns', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('urban_rural_access', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('climate_considerations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('local_cuisine_integration', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('community_dining_patterns', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('past_diet_experiences', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('relationship_with_food_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('eating_patterns_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hydration_habits', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('current_supplements', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('performance_nutrition_needs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gut_health_concerns', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('current_weekly_meal_plan', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('meal_plan_start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('special_dietary_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint('cooking_confidence_rating >= 1 AND cooking_confidence_rating <= 10', name=op.f('dietitian_profiles_cooking_confidence_rating_check')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('dietitian_profiles_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dietitian_profile_id', name=op.f('dietitian_profiles_pkey'))
    )
    op.create_table('vector_embeddings',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('vector_embeddings_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('vector_embeddings_pkey'))
    )
    op.create_index(op.f('idx_vector_embeddings_user_category'), 'vector_embeddings', ['user_id', 'category'], unique=False)
    op.create_index(op.f('idx_vector_embeddings_embedding'), 'vector_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='ivfflat')
    op.create_table('daily_tracking_entries',
    sa.Column('entry_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('entry_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('sleep_duration_hours', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    sa.Column('sleep_quality_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('energy_level_morning', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('energy_level_afternoon', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('energy_level_evening', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('physical_activity_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('physical_activity_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meal_plan_adherence_percentage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hydration_glasses_water', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('physical_symptoms', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mood_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mood_context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stress_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stress_triggers_encountered', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('anxiety_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('positive_moments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gratitude_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('social_interactions_quality', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('coping_strategies_used', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('fitness_goals_progress', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('nutrition_goals_progress', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('wellness_goals_progress', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('challenges_faced', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('successes_celebrated', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('work_life_balance_today', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('personal_time_satisfaction', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('motivation_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('daily_reflection', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tomorrow_intentions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tracker_agent_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint('anxiety_level >= 1 AND anxiety_level <= 10', name=op.f('daily_tracking_entries_anxiety_level_check')),
    sa.CheckConstraint('energy_level_afternoon >= 1 AND energy_level_afternoon <= 10', name=op.f('daily_tracking_entries_energy_level_afternoon_check')),
    sa.CheckConstraint('energy_level_evening >= 1 AND energy_level_evening <= 10', name=op.f('daily_tracking_entries_energy_level_evening_check')),
    sa.CheckConstraint('energy_level_morning >= 1 AND energy_level_morning <= 10', name=op.f('daily_tracking_entries_energy_level_morning_check')),
    sa.CheckConstraint('meal_plan_adherence_percentage >= 0 AND meal_plan_adherence_percentage <= 100', name=op.f('daily_tracking_entries_meal_plan_adherence_percentage_check')),
    sa.CheckConstraint('mood_rating >= 1 AND mood_rating <= 10', name=op.f('daily_tracking_entries_mood_rating_check')),
    sa.CheckConstraint('motivation_level >= 1 AND motivation_level <= 10', name=op.f('daily_tracking_entries_motivation_level_check')),
    sa.CheckConstraint('personal_time_satisfaction >= 1 AND personal_time_satisfaction <= 10', name=op.f('daily_tracking_entries_personal_time_satisfaction_check')),
    sa.CheckConstraint('sleep_quality_rating >= 1 AND sleep_quality_rating <= 10', name=op.f('daily_tracking_entries_sleep_quality_rating_check')),
    sa.CheckConstraint('social_interactions_quality >= 1 AND social_interactions_quality <= 10', name=op.f('daily_tracking_entries_social_interactions_quality_check')),
    sa.CheckConstraint('stress_level >= 1 AND stress_level <= 10', name=op.f('daily_tracking_entries_stress_level_check')),
    sa.CheckConstraint('work_life_balance_today >= 1 AND work_life_balance_today <= 10', name=op.f('daily_tracking_entries_work_life_balance_today_check')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('daily_tracking_entries_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id', name=op.f('daily_tracking_entries_pkey')),
    sa.UniqueConstraint('user_id', 'entry_date', name=op.f('daily_tracking_entries_user_id_entry_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_daily_tracking_user_date'), 'daily_tracking_entries', ['user_id', 'entry_date'], unique=False)
    op.create_table('dim_user',
    sa.Column('user_key', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('age_group', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('gender_identity', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('location_region', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('occupation_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('dim_user_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_key', name=op.f('dim_user_pkey'))
    )
    op.create_table('agent_conversations',
    sa.Column('conversation_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('agent_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('message_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('context_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('agent_conversations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', name=op.f('agent_conversations_pkey'))
    )
    op.create_index(op.f('idx_conversations_user_agent'), 'agent_conversations', ['user_id', 'agent_type'], unique=False)
    op.create_index(op.f('idx_conversations_session'), 'agent_conversations', ['session_id'], unique=False)
    op.create_table('dim_date',
    sa.Column('date_key', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('day_name', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('month_name', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('quarter', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_weekend', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('week_of_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('date_key', name=op.f('dim_date_pkey'))
    )
    op.create_table('tracker_profiles',
    sa.Column('tracker_profile_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('preferred_check_in_time', postgresql.TIME(), server_default=sa.text("'20:00:00'::time without time zone"), autoincrement=False, nullable=True),
    sa.Column('tracking_frequency', sa.VARCHAR(length=50), server_default=sa.text("'daily'::character varying"), autoincrement=False, nullable=True),
    sa.Column('preferred_tracking_methods', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('motivation_style', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('celebration_preferences', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('accountability_style', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('mood_tracking_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('energy_tracking_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('sleep_tracking_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('activity_tracking_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('nutrition_tracking_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('stress_tracking_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('custom_tracking_categories', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('weekly_summary_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('trend_analysis_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('goal_progress_alerts', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('challenge_area_focus', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('success_celebration_frequency', sa.VARCHAR(length=50), server_default=sa.text("'weekly'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('tracker_profiles_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tracker_profile_id', name=op.f('tracker_profiles_pkey'))
    )
    op.create_table('dim_agent',
    sa.Column('agent_key', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('agent_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('agent_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('agent_role', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('agent_key', name=op.f('dim_agent_pkey'))
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('trainer_profiles',
    sa.Column('trainer_profile_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('current_fitness_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('previous_exercise_experience', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('preferred_activities', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('available_equipment', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('gym_access_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('workout_time_preference', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('weekly_time_availability', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('daily_time_slots', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('physical_limitations_fitness', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('injury_history', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('primary_fitness_goals', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('target_timeline', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('current_measurements', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('desired_changes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('performance_benchmarks', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('body_composition_goals', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('functional_fitness_needs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('work_energy_patterns', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('home_workout_setup', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('travel_frequency', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('schedule_variability', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('family_commitments_affecting_workouts', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('seasonal_preferences', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fitness_budget_range', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('current_weekly_plan', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('plan_start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('plan_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('trainer_profiles_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trainer_profile_id', name=op.f('trainer_profiles_pkey'))
    )
    # ### end Alembic commands ###
