"""initial migration

Revision ID: 73bcfe3eb80e
Revises: 
Create Date: 2026-03-28 13:40:09.280428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73bcfe3eb80e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create Priority Enum type manually since autogenerate missed the type creation sometimes
    sa.Enum('high', 'medium', 'low', 'pending', name='priorityenum').create(op.get_bind())
    sa.Enum('user', 'assistant', name='roleenum').create(op.get_bind())
    
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('preference', sa.String(), nullable=True),
    sa.Column('timeline_months', sa.Integer(), nullable=True),
    sa.Column('priority', postgresql.ENUM('high', 'medium', 'low', 'pending', name='priorityenum', create_type=False), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('follow_up_count', sa.Integer(), nullable=False),
    sa.Column('follow_up_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_session_id'), 'leads', ['session_id'], unique=True)
    
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('role', postgresql.ENUM('user', 'assistant', name='roleenum', create_type=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_hash', sa.String(length=64), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'message_hash', name='uix_session_message_hash')
    )
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_leads_session_id'), table_name='leads')
    op.drop_table('leads')
    sa.Enum(name='priorityenum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='roleenum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
